services:
  app:
    build: .
    container_name: "mailing_app"
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - JWT_SECRET=your_jwt_secret
      - JWT_ISSUER=mailmanager
      - SMTP_HOST=smtp.example.com
      - SMTP_USER=your_smtp_user
      - SMTP_PASS=your_smtp_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mailmanager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - DEBUG=true
    restart: unless-stopped

  postgres:
    container_name: "mailing_db"
    image: postgres:14-alpine
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mailmanager
    ports:
      - "5433:5432"  # Changed from 5432:5432
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge