services:
  app:
    build: .
    container_name: "mailing_app"
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ".env"
    restart: unless-stopped

  postgres:
    container_name: "mailing_db"
    image: postgres:14-alpine
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    container_name: "mailing_redis"
    image: redis:7-alpine
    networks:
      - app-network
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge